### PR TITLE
ncsi-netlink: support sending NC-SI command over Netlink interface

### PR DESCRIPTION
**Pull request by benwei13**
This patch extends ncsi-netlink command line utility to send NC-SI
command to kernel driver via NCSI_CMD_SEND_CMD command.

New command line option -o (opcode) is used to specify NC-SI command
and optional payload.

For example, to send "Get Parameter" command

      ncsi-netlink -l 2 -c 0 -p0 -o 0x17

To configure AEN

      ncsi-netlink -l 2 -c 0 -p0 -o 8 0 0 0 0 0 0 0 7

Signed-off-by: Ben Wei <benwei@fb.com>

### CODE REVIEW

**Comment by sammj** [comment]
Hi @benwei13, thanks for the improvements! Just for completeness can you give a quick description of how you tested it and an example of the output? Otherwise this looks fine :+1:

**Comment by benwei13** [comment]
Hi @sammj, 
sure.  I need to add a recipe for this to Yocto, but for testing, I add this to our BMC platform, and tried a few NC-SI commands from user space.

Sample output: 

1. Test sending cmd, no payload, just opcode  - get link status

root@bmc-oob:~# ncsi-netlink -l 2 -c 0 -p0 -o 0xa
Response Code: 0x0000  Reason Code: 0x0000
Response Payload:
0x00 0x00 0x00 0x00
20: 0x00 0x07 0x52 0x6f
24: 0x00 0x00 0x00 0x01
28: 0x00 0x00 0x00 0x00
32: 0x00 0x00 0x00 0x00
36: 0x00 0x00 0x00 0x00
40: 0x00 0x00 0x00 0x00
44: 0x00 0x00 0xe7 0x91
48: 0x1b 0x01

2. Test sending cmd, no payload, just opcode  - get parameters
root@fa002-du013-oob:~# ncsi-netlink -l 2 -c 0 -p0 -o 0x17
Response Code: 0x0000  Reason Code: 0x0000
Response Payload:
0x00 0x00 0x00 0x00
20: 0x0c 0x00 0x00 0x01
24: 0x02 0x00 0x00 0x00
28: 0x00 0x00 0x03 0x0f
32: 0x00 0x00 0x00 0x0f
36: 0x00 0x00 0x00 0x0f
40: 0x00 0x03 0x00 0x00
44: 0x00 0x00 0x00 0x07
48: 0x98 0x5d 0x82 0x09
52: 0x27 0xa0 0x00 0x00
56: 0x00 0x00 0x00 0x00
60: 0x00 0x00 0x00 0x00
64: 0x00 0x00 0x00 0x00
68: 0x00 0x00 0x00 0x00
72: 0x00 0x00 0x00 0x00
76: 0x00 0x00 0x00 0x00
80: 0x00 0x00 0x00 0x00
84: 0x00 0x00 0x00 0x00
88: 0x00 0x00 0x00 0x00
92: 0x00 0x00 0x00 0x00
96: 0x00 0x00 0x00 0x00
100: 0x00 0x00 0x00 0x00
104: 0x00 0x00 0x00 0x00
108: 0x00 0x00 0x00 0x00
112: 0x00 0x00 0x00 0x00
116: 0x00 0x00 0x00 0x00
120: 0x00 0x00 0x00 0x00
124: 0x00 0x00 0x00 0x00
128: 0x99 0xc4 0x11 0x5d


(current AEN setting at offset 47 = 0x7)

3. Test sending cmd with payload - change AEN setting to 1

root@bmc-oob:~# ncsi-netlink -l 2 -c 0 -p0 -o 8 0 0 0 0 0 0 0 1
Response Code: 0x0000  Reason Code: 0x0000
Response Payload:
0x00 0x00 0x00 0x00
20: 0x00 0x00 0x00 0x00
24: 0x00 0x00 0x00 0x00
28: 0x00 0x00 0x00 0x00
32: 0x00 0x00 0x00 0x00
36: 0x00 0x00 0x00 0x00
40: 0x00 0x00 0x00 0x00
44: 0x00 0x00 0xbe 0xec
48: 0x25 0x18


4. get parameter again and verify AEN setting has been updated
root@bmc-oob:~# ncsi-netlink -l 2 -c 0 -p0 -o 0x17 | grep 44
44: 0x00 0x00 0x00 0x01

**Comment by benwei13** [comment]
Also probably having some sort of response parsing (for cmds like get various statistics, get capability/parameters)  would be useful, I can add additional PRs on this

**Comment by shenki** [comment]
@sammj can you merge this please?

**Comment by sammj** [comment]
Thanks for the reminder @shenki - looks good @benwei13 , merged!

**Pull request merged**
